import type { GameModeConfig } from "@/types/game";

export const APP_NAME = "JW Games";
export const APP_TAGLINE = "Apprenez la Bible en vous amusant";

export const XP_PER_LEVEL = 500;
export const DAILY_CHALLENGE_BONUS = 100;
export const VIDEO_WATCH_XP = 25;

export const GAME_MODES: GameModeConfig[] = [
  {
    id: "videoquiz",
    title: "Vidéo Quiz",
    description: "Regardez une vidéo JW.org puis répondez à des questions.",
    icon: "🎬",
    color: "from-teal-500 to-teal-600",
    href: "/jeux/video-quiz",
    players: "solo",
    available: true,
    tag: "Nouveau",
  },
  {
    id: "vraifaux",
    title: "Vrai ou Faux",
    description: "Séparez le vrai du faux en un clin d'œil.",
    icon: "✅",
    color: "from-emerald-500 to-emerald-600",
    href: "/jeux/vrai-faux",
    players: "solo",
    available: true,
    tag: "Nouveau",
  },
  {
    id: "ordre",
    title: "Ordre chronologique",
    description: "Remettez les événements bibliques dans le bon ordre.",
    icon: "📅",
    color: "from-orange-500 to-orange-600",
    href: "/jeux/ordre",
    players: "solo",
    available: true,
    tag: "Nouveau",
  },
  {
    id: "mots",
    title: "Mots mélangés",
    description: "Retrouvez le mot biblique caché parmi les lettres.",
    icon: "🔤",
    color: "from-violet-500 to-violet-600",
    href: "/jeux/mots",
    players: "solo",
    available: true,
    tag: "Nouveau",
  },
  {
    id: "versets",
    title: "Versets à trous",
    description: "Complétez les versets de la Traduction du monde nouveau.",
    icon: "✍️",
    color: "from-blue-500 to-blue-600",
    href: "/jeux/versets",
    players: "solo",
    available: true,
    tag: "Nouveau",
  },
  {
    id: "cartes",
    title: "Cartes mémoire",
    description: "Révisez personnages, versets et faits bibliques.",
    icon: "🃏",
    color: "from-amber-500 to-amber-600",
    href: "/jeux/cartes",
    players: "solo",
    available: true,
    tag: "Nouveau",
  },
  {
    id: "undercover",
    title: "Undercover",
    description: "Jeu de groupe 3–12 joueurs : mots bibliques, bluff et vote.",
    icon: "🕵️",
    color: "from-purple-500 to-purple-600",
    href: "/jeux/undercover",
    players: "multi",
    available: true,
  },
  {
    id: "quiz",
    title: "Quiz biblique",
    description: "Testez vos connaissances avec des questions à choix multiples.",
    icon: "📖",
    color: "from-teal-600 to-cyan-600",
    href: "/jeux/quiz",
    players: "both",
    available: true,
  },
  {
    id: "rapidite",
    title: "Rapidité",
    description: "Répondez le plus vite possible aux défis bibliques.",
    icon: "⚡",
    color: "from-yellow-500 to-amber-500",
    href: "/jeux/rapidite",
    players: "solo",
    available: true,
  },
  {
    id: "memoire",
    title: "Mémoire",
    description: "Associez versets, personnages et événements bibliques.",
    icon: "🧠",
    color: "from-green-500 to-green-600",
    href: "/jeux/memoire",
    players: "solo",
    available: true,
  },
  {
    id: "thematique",
    title: "Thématiques",
    description: "Questionnaires par thème : prophéties, paraboles, personnages…",
    icon: "🎯",
    color: "from-rose-500 to-rose-600",
    href: "/jeux/thematique",
    players: "both",
    available: true,
  },
  {
    id: "equipe",
    title: "Défis en équipe",
    description: "Deux équipes s'affrontent sur des questions bibliques.",
    icon: "👥",
    color: "from-sky-500 to-sky-600",
    href: "/jeux/equipe",
    players: "multi",
    available: true,
  },
  {
    id: "devinettes",
    title: "Devinettes bibliques",
    description: "Répondez à des énigmes inspirées des Écritures.",
    icon: "💡",
    color: "from-yellow-400 to-orange-500",
    href: "/jeux/devinettes",
    players: "solo",
    available: true,
    tag: "Nouveau",
  },
  {
    id: "biblio",
    title: "Livres de la Bible",
    description: "Remettez les livres bibliques dans le bon ordre.",
    icon: "📚",
    color: "from-indigo-500 to-blue-600",
    href: "/jeux/biblio",
    players: "solo",
    available: true,
    tag: "Nouveau",
  },
  {
    id: "quotidien",
    title: "Défi quotidien",
    description: "Un nouveau défi chaque jour pour maintenir votre série !",
    icon: "🔥",
    color: "from-orange-500 to-red-500",
    href: "/quotidien",
    players: "solo",
    available: true,
  },
];

export const DIFFICULTY_LABELS = {
  facile: "Facile",
  moyen: "Moyen",
  difficile: "Difficile",
  expert: "Expert",
} as const;

export const OFFICIAL_SOURCES_NOTICE =
  "Tout le contenu est basé exclusivement sur les sources officielles : JW.org et JW Library (Traduction du monde nouveau).";
