def q(question, options, correctIndex, explanation):
    return {"question": question, "options": options, "correctIndex": correctIndex, "explanation": explanation}

def e(scripture, reference, thought, q1, q2, q3, q4):
    return {"scripture": scripture, "reference": reference, "thought": thought, "questions": [q1, q2, q3, q4]}

ENTRIES = [
e("Jéhovah est mon berger. Je ne manquerai de rien.", "Psaume 23:1",
  "David compare Jéhovah à un berger attentif. Cette image rassure : notre Créateur connaît nos besoins et guide nos pas avec tendresse.",
  q("Que symbolise le « berger » en Psaume 23:1 ?", ["Jéhovah qui veille sur nous", "Un roi humain", "Un ange gardien", "Un prophète"], 0, "David compare Jéhovah à un berger protecteur."),
  q("Qui a écrit le Psaume 23 ?", ["David", "Moïse", "Salomon", "Ésaïe"], 0, "David, ancien berger, a composé ce psaume."),
  q("« Je ne manquerai de rien » exprime surtout…", ["La confiance en la provision de Jéhovah", "Une richesse garantie", "L'absence d'épreuves", "L'autonomie totale"], 0, "David fait confiance à Jéhovah pour pourvoir à ses besoins."),
  q("Psaume 23:2 évoque des « eaux paisibles ». Que signifient-elles ?", ["Repos et restauration divins", "La mer Morte", "Un puits creusé par David", "La pluie du désert"], 0, "Jéhovah restaure ceux qui le suivent.")),

e("Confie-toi en Jéhovah de tout ton cœur, et ne t'appuie pas sur ta propre intelligence.", "Proverbes 3:5",
  "La sagesse humaine a ses limites. Reconnaître Jéhovah dans nos décisions ouvre la voie à sa direction bienveillante.",
  q("Que signifie « confie-toi en Jéhovah de tout ton cœur » ?", ["Lui faire entièrement confiance", "Ne jamais réfléchir", "Suivre ses émotions", "Ignorer la Bible"], 0, "Il s'agit d'une confiance sincère et totale."),
  q("Que nous est-il déconseillé de faire selon ce verset ?", ["Nous appuyer uniquement sur notre intelligence", "Prier", "Étudier", "Demander conseil"], 0, "Notre raisonnement seul ne voit pas l'avenir."),
  q("Proverbes 3:6 promet que Jéhovah dirigera nos sentiers si…", ["Nous le reconnaissons dans toutes nos voies", "Nous agissons seuls", "Nous refusons la prière", "Nous ignorons sa Parole"], 0, "Reconnaître Jéhovah inclut nos choix quotidiens."),
  q("Quel exemple illustre cette confiance ?", ["Abraham quittant Ur", "La tour de Babel", "Judas", "Ananias"], 0, "Abraham est parti sans connaître sa destination.")),

e("Ne vous inquiétez de rien, mais en toute chose faites connaître vos besoins à Dieu par des prières et des supplications.", "Philippiens 4:6",
  "Paul encourage les chrétiens de Philippes à remplacer l'inquiétude par la prière. Parler à Jéhovah de nos préoccupations apporte une paix unique.",
  q("Que propose Paul au lieu de s'inquiéter ?", ["Prier et présenter nos besoins", "Tout garder secret", "Murmurer", "Abandonner la foi"], 0, "La prière remplace l'inquiétude excessive."),
  q("Comment faire connaître nos besoins à Dieu ?", ["Par des prières et supplications", "Par des songes seulement", "En silence total", "Sans lui parler"], 0, "La prière est une communication directe."),
  q("Philippiens 4:7 promet après la prière…", ["La paix de Dieu gardera nos cœurs", "La richesse immédiate", "Zéro problème", "Un sommeil forcé"], 0, "Cette paix surpasse toute pensée humaine."),
  q("À qui Paul écrit-il cette lettre ?", ["Aux chrétiens de Philippes", "Au sanhédrin", "À l'empereur", "Aux pharisiens"], 0, "Philippi était une colonie romaine en Macédoine.")),

e("Aimez-vous les uns les autres ; tout comme je vous ai aimés, aimez-vous les uns les autres.", "Jean 13:34",
  "Jésus donne un commandement nouveau : s'aimer comme il nous a aimés. Cet amour désintéressé identifie les vrais disciples.",
  q("Quel est le « commandement nouveau » de Jean 13:34 ?", ["S'aimer comme Jésus nous a aimés", "Observer le sabbat", "Jeûner chaque semaine", "Construire un temple"], 0, "Jésus définit l'amour fraternel comme marque distinctive."),
  q("Quel geste de Jésus précède ce commandement dans Jean 13 ?", ["Le lavement des pieds", "La multiplication des pains", "La transfiguration", "La marche sur l'eau"], 0, "Jésus illustre l'humilité par le service."),
  q("Selon Jean 13:35, comment le monde reconnaîtra-t-il les disciples ?", ["À l'amour qu'ils ont les uns pour les autres", "À leurs riches vêtements", "À leur nombre", "À leurs titres"], 0, "L'amour fraternel est le signe visible de la vraie foi."),
  q("L'amour décrit ici implique surtout…", ["Donner de soi au service des autres", "Ignorer toute faute", "N'aimer que sa famille", "Attendre d'être aimé d'abord"], 0, "Jésus a donné sa vie ; nous imitons cet amour actif.")),

e("Soyez imitaeurs de Dieu, comme des enfants bien-aimés.", "Éphésiens 5:1",
  "Paul exhorte les chrétiens d'Éphèse à refléter les qualités de Jéhovah. Imiter Dieu transforme notre conduite quotidienne.",
  q("Que signifie « imitaeurs de Dieu » ?", ["Reproduire ses qualités morales", "Prétendre être divins", "Créer des idoles", "Ignorer ses lois"], 0, "Imiter Jéhovah, c'est refléter son amour et sa justice."),
  q("À quoi Paul compare-t-il les chrétiens ?", ["Des enfants bien-aimés", "Des soldats", "Des marchands", "Des étrangers"], 0, "Un enfant imite un parent qu'il aime."),
  q("Éphésiens 5:2 invite à marcher dans l'amour en imitant…", ["Christ qui s'est offert pour nous", "Salomon et ses richesses", "David et ses conquêtes", "Moïse seul"], 0, "Jésus est le modèle suprême de l'amour sacrificiel."),
  q("Imiter Dieu exclut quelle conduite (v. 3-4) ?", ["L'immoralité et la parole grossière", "La prière matinale", "L'étude biblique", "Le service aux autres"], 0, "Paul lie l'imitation de Dieu à une conduite pure.")),

e("Tout ce que vous voulez que les hommes vous fassent, faites-leur de même.", "Matthieu 7:12",
  "Jésus résume la loi morale en une règle simple : traiter autrui comme nous voulons être traités. C'est le fondement de l'amour du prochain.",
  q("Comment Jésus appelle-t-il cette règle en Matthieu 7:12 ?", ["La loi et les prophètes", "Le sabbat", "Le jeûne", "Le sacrifice"], 0, "Jésus dit que cette règle résume la loi et les prophètes."),
  q("Cette règle demande de…", ["Traiter les autres comme on veut être traité", "Exiger le respect sans le donner", "Ignorer les autres", "Ne penser qu'à soi"], 0, "C'est le principe de réciprocité dans l'amour."),
  q("Dans quel discours Jésus prononce-t-il Matthieu 7:12 ?", ["Le Sermon sur la montagne", "La dernière Cène", "Au temple à 12 ans", "Sur le bateau"], 0, "Ce verset fait partie du Sermon sur la montagne."),
  q("Appliquer Matthieu 7:12 au quotidien signifie…", ["Considérer les sentiments d'autrui avant d'agir", "Ne jamais corriger", "Toujours céder", "Éviter toute relation"], 0, "L'amour du prochain guide nos paroles et actes.")),

e("La crainte de Jéhovah est le commencement de la sagesse.", "Proverbes 9:10",
  "Le respect profond pour Jéhovah est le fondement de toute vraie sagesse. Sans lui, notre connaissance reste incomplète.",
  q("Que signifie « la crainte de Jéhovah » ici ?", ["Un profond respect et révérence", "Une terreur paralysante", "L'indifférence", "La haine de Dieu"], 0, "C'est un respect révérenciel, pas une peur panique."),
  q("Cette crainte est appelée le « commencement » de quoi ?", ["De la sagesse", "De la richesse", "De la guerre", "De la tristesse"], 0, "Toute sagesse véritable commence par reconnaître Jéhovah."),
  q("Proverbes 9:10 ajoute que la connaissance du Saint est…", ["De l'intelligence", "De l'orgueil", "De la paresse", "De la superstition"], 0, "Connaître Jéhovah approfondit notre intelligence."),
  q("Quel livre contient ce proverbe ?", ["Proverbes", "Psaumes", "Genèse", "Apocalypse"], 0, "Proverbes regroupe la sagesse pratique inspirée.")),

e("Continuez plutôt à chercher en priorité le royaume et sa justice, et toutes ces autres choses vous seront ajoutées.", "Matthieu 6:33",
  "Jésus enseigne à placer les intérêts spirituels avant les préoccupations matérielles. Jéhovah pourvoit quand nos priorités sont justes.",
  q("Que devons-nous chercher « en priorité » selon Matthieu 6:33 ?", ["Le royaume et sa justice", "La richesse", "La célébrité", "Le repos permanent"], 0, "Les priorités spirituelles passent avant tout."),
  q("Que promet Jésus si nous mettons le royaume en premier ?", ["Que les autres choses seront ajoutées", "Qu'on n'aura plus de besoins", "Qu'on sera toujours riche", "Qu'on n'aura plus à travailler"], 0, "Jéhovah pourvoit selon sa sagesse."),
  q("Matthieu 6:33 fait suite à un avertissement contre…", ["L'inquiétude excessive pour la nourriture et les vêtements", "La prière", "L'étude biblique", "Le service"], 0, "Jésus dénonce l'inquiétude matérielle avant ce verset."),
  q("Mettre le royaume en priorité affecte surtout…", ["Nos choix de vie et notre temps", "Notre couleur préférée", "Notre lieu de naissance", "Notre taille"], 0, "Nos décisions reflètent nos priorités.")),

e("Soyez faibles envers les uns envers les autres, avec humilité et patience.", "Éphésiens 4:2",
  "Paul exhorte les chrétiens à faire preuve d'humilité et de patience dans leurs relations. Ces qualités préservent l'unité de la congrégation.",
  q("Quelles qualités Paul associe-t-il en Éphésiens 4:2 ?", ["Humilité et patience", "Orgueil et impatience", "Richesse et pouvoir", "Silence et isolement"], 0, "L'humilité et la patience maintiennent l'unité."),
  q("« Soyez faibles envers les uns envers les autres » signifie surtout…", ["Faire preuve de douceur et de tolérance", "Être physiquement faibles", "Ne jamais parler", "Accepter toute injustice"], 0, "La douceur caractérise les relations chrétiennes."),
  q("Éphésiens 4:3 exhorte à préserver l'unité par…", ["Le lien de la paix", "La compétition", "L'isolement", "La critique constante"], 0, "La paix unit les disciples de Christ."),
  q("Pourquoi l'humilité est-elle essentielle dans une congrégation ?", ["Elle évite les divisions et l'orgueil", "Elle garantit la richesse", "Elle supprime la prière", "Elie rend inutile l'étude"], 0, "L'orgueil divise ; l'humilité unit.")),

e("Heureux l'homme qui endure l'épreuve, car une fois approuvé, il recevra la couronne de la vie.", "Jacques 1:12",
  "Jacques rappelle que l'endurance sous l'épreuve mène à la récompense promise. Tenir bon renforce notre foi et notre espérance.",
  q("Qui est « heureux » selon Jacques 1:12 ?", ["Celui qui endure l'épreuve", "Celui qui évite toute difficulté", "Celui qui se plaint", "Celui qui abandonne"], 0, "L'endurance sous l'épreuve est valorisée."),
  q("Quelle récompense est promise à celui qui endure ?", ["La couronne de la vie", "Une couronne d'or terrestre", "La richesse immédiate", "Le pouvoir politique"], 0, "La couronne de la vie est la récompense éternelle."),
  q("Jacques 1:12 précise que Jéhovah a promis la couronne à qui ?", ["À ceux qui l'aiment", "À ceux qui le renient", "Aux incrédules", "Aux fainéants"], 0, "L'amour pour Jéhovah motive l'endurance."),
  q("Endurer l'épreuve implique…", ["Tenir bon malgré les difficultés", "Nier l'existence de l'épreuve", "Blâmer les autres", "Abandonner la foi"], 0, "L'endurance est une qualité active, pas passive.")),

e("Louez Jéhovah, car il est bon ; car sa bonté dure à toujours.", "Psaume 106:1",
  "Le psalmiste appelle à louer Jéhovah pour sa bonté permanente. La gratitude nous aide à voir ses bienfaits même dans les moments difficiles.",
  q("Pour quelle raison louer Jéhovah en Psaume 106:1 ?", ["Parce qu'il est bon et que sa bonté dure", "Parce qu'il est lointain", "Parce qu'il ignore nos prières", "Parce qu'il change sans cesse"], 0, "Sa bonté est permanente et mérite notre louange."),
  q("« Sa bonté dure à toujours » signifie…", ["Elle ne prend jamais fin", "Elle dure une journée", "Elle dépend de nos actes", "Elle est incertaine"], 0, "La bonté de Jéhovah est éternelle."),
  q("Louer Jéhovah implique surtout…", ["Exprimer gratitude et reconnaissance", "Se taire complètement", "Se vanter soi-même", "Critiquer les autres"], 0, "La louange honore notre Créateur."),
  q("Psaume 106 rappelle aussi les fautes d'Israël pour…", ["Montrer la fidélé de Jéhovah malgré l'infidélité humaine", "Glorifier le péché", "Oublier l'histoire", "Nier les miracles"], 0, "Jéhovah reste fidèle même quand les hommes faillissent.")),

e("Celui qui endure jusqu'à la fin sera sauvé.", "Matthieu 24:13",
  "Jésus met en garde ses disciples : la persévérance jusqu'à la fin est essentielle. Tenir bon dans la foi n'est pas optionnel.",
  q("Qui « sera sauvé » selon Matthieu 24:13 ?", ["Celui qui endure jusqu'à la fin", "Celui qui commence seulement", "Celui qui abandonne", "Celui qui nie la foi"], 0, "La persévérance jusqu'à la fin est requise."),
  q("Dans quel contexte Jésus prononce-t-il Matthieu 24:13 ?", ["La prophétie sur la fin du système", "La multiplication des pains", "Le baptême", "La naissance"], 0, "Ce verset fait partie de la prophétie sur les derniers jours."),
  q("Endurer « jusqu'à la fin » implique…", ["Persévérer dans la foi malgré les épreuves", "Tenir quelques jours seulement", "Suivre la mode", "Changer d'avis souvent"], 0, "La fidélité doit durer toute notre vie."),
  q("Pourquoi Jésus insiste-t-il sur l'endurance ici ?", ["Parce que la fidélité sera mise à l'épreuve", "Parce que la fin n'arrivera jamais", "Parce que personne ne sera testé", "Parce que la foi est facile"], 0, "Les derniers jours exigeront une fidélité constante.")),

e("Jéhovah est ma lumière et mon salut. De qui aurais-je crainte ?", "Psaume 27:1",
  "David proclame sa confiance en Jéhovah comme source de lumière et de salut. Quand Jéhovah est avec nous, la crainte des hommes perd de son poids.",
  q("Comment David qualifie-t-il Jéhovah en Psaume 27:1 ?", ["Ma lumière et mon salut", "Mon ennemi", "Mon juge distant", "Mon oubli"], 0, "Jéhovah éclaire et sauve David."),
  q("« De qui aurais-je crainte ? » exprime…", ["La confiance de David malgré les menaces", "La peur de tout", "L'indifférence", "L'orgueil"], 0, "Avec Jéhovah, David ne craint pas ses adversaires."),
  q("Psaume 27:4 montre la priorité de David : demeurer…", ["Dans la maison de Jéhovah", "Dans un palais étranger", "Seul dans le désert", "Loin de toute prière"], 0, "David désire ardemment la présence de Jéhovah."),
  q("La « lumière » de Jéhovah représente…", ["Sa guidance et sa vérité", "Un feu destructeur", "L'obscurité", "L'ignorance"], 0, "Jéhovah éclaire le chemin de ses serviteurs.")),

e("Car je connais les projets que j'ai formés à votre égard, déclare Jéhovah, projets de paix et non de calamité.", "Jérémie 29:11",
  "Jéhovah rassure son peuple exilé : ses desseins sont bons, orientés vers l'espérance. Même dans l'épreuve, ses projets visent la paix.",
  q("Quel type de projets Jéhovah forme-t-il selon Jérémie 29:11 ?", ["Des projets de paix, non de calamité", "Des projets de destruction", "Des projets sans but", "Des projets de guerre"], 0, "Jéhovah veut le bien-être de son peuple."),
  q("À qui Jéhovah s'adresse-t-il dans Jérémie 29:11 ?", ["Aux exilés à Babylone", "Aux Égyptiens", "Aux Romains", "Aux Grecs"], 0, "Israël était en exil ; Jéhovah les rassure."),
  q("Jérémie 29:11 promet « un avenir et une espérance ». Cela signifie…", ["Jéhovah a un plan favorable pour son peuple", "Il n'y a aucun avenir", "L'espérance est interdite", "Tout est désespéré"], 0, "Jéhovah offre un avenir plein d'espérance."),
  q("Comment réagir quand les circonstances semblent calamiteuses ?", ["Se rappeler que Jéhovah a des projets de paix", "Abandonner la foi", "Blâmer Jéhovah", "Nier ses promesses"], 0, "Ses desseins dépassent ce que nous voyons.")),

e("L'amour ne travaille pas le mal envers le prochain. L'amour est donc la loi qui accomplit toute autre loi.", "Romains 13:10",
  "Paul explique que l'amour véritable respecte autrui et accomplit naturellement les exigences morales. L'amour est le principe unificateur de la loi de Dieu.",
  q("Que l'amour ne fait-il pas selon Romains 13:10 ?", ["Travailler le mal envers le prochain", "Aider le prochain", "Pardonner", "Encourager"], 0, "L'amour sincère ne nuit jamais à autrui."),
  q("Paul dit que l'amour accomplit…", ["Toute autre loi", "Rien du tout", "Seulement le sabbat", "Uniquement les dîmes"], 0, "L'amour résume et accomplit les exigences morales."),
  q("Romains 13:9 cite plusieurs commandements et conclut qu'ils se résument en…", ["Aimer son prochain comme soi-même", "Haïr ses ennemis", "Ignorer les autres", "Ne jamais corriger"], 0, "L'amour du prochain résume la loi."),
  q("Appliquer Romains 13:10 au quotidien signifie…", ["Agir avec bienveillance envers autrui", "Ne jamais parler", "Éviter toute relation", "Ne penser qu'à soi"], 0, "L'amour guide nos paroles et nos actes.")),

e("Soyez toujours joyeux. Priez sans cesse. Rendez grâces en toute circonstance.", "1 Thessaloniciens 5:16-18",
  "Paul résume l'attitude chrétienne en trois exhortations : joie, prière constante et gratitude. Ces habitudes nourrissent notre relation avec Jéhovah.",
  q("Combien d'exhortations Paul donne-t-il en 1 Thessaloniciens 5:16-18 ?", ["Trois : joie, prière, gratitude", "Une seule", "Dix", "Aucune"], 0, "Trois attitudes fondamentales sont mentionnées."),
  q("« Priez sans cesse » signifie…", ["Avoir une attitude de prière régulière", "Prier 24 h sans dormir", "Ne jamais parler", "Prier une fois par an"], 0, "C'est une prière fréquente et constante, pas ininterrompue."),
  q("« Rendez grâces en toute circonstance » implique…", ["Trouver des raisons de remercier même dans l'épreuve", "Remercier seulement quand tout va bien", "Ignorer les difficultés", "Ne jamais prier"], 0, "La gratitude s'étend à toutes les situations."),
  q("Paul ajoute en v. 18 que rendre grâces est…", ["La volonté de Dieu en Christ", "Optionnel", "Interdit", "Réservé aux anciens"], 0, "La gratitude fait partie de la volonté de Dieu pour nous.")),

e("Car c'est par la grâce que vous avez été sauvés, par le moyen de la foi ; et cela ne vient pas de vous, c'est le don de Dieu.", "Éphésiens 2:8",
  "Paul rappelle que le salut repose sur la grâce de Dieu et la foi, non sur nos mérites. Reconnaître ce don humble notre cœur.",
  q("Par quoi sommes-nous sauvés selon Éphésiens 2:8 ?", ["Par la grâce, par le moyen de la foi", "Par nos propres œuvres seules", "Par la richesse", "Par la naissance"], 0, "Le salut est un don de la grâce de Dieu."),
  q("« Cela ne vient pas de vous » signifie…", ["Le salut n'est pas mérité par nos efforts", "Nous n'avons aucun rôle", "La foi est inutile", "Dieu ne donne rien"], 0, "Nous ne pouvons pas nous sauver nous-mêmes."),
  q("Éphésiens 2:9 précise que le salut n'est pas le résultat de…", ["Nos œuvres, pour que personne ne se glorifie", "Notre foi", "La grâce de Dieu", "La prière"], 0, "Personne ne peut se glorifier de s'être sauvé lui-même."),
  q("La grâce de Dieu est décrite comme…", ["Un don", "Un salaire gagné", "Une punition", "Une dette"], 0, "Le salut est un don gratuit, non un salaire.")),

e("Car tout ce qui a été écrit auparavant a été écrit pour notre instruction.", "Romains 15:4",
  "Paul souligne que les Écritures hébraïques ont été consignées pour nous enseigner et nous donner espérance. L'étude biblique n'est pas une formalité.",
  q("Pourquoi les Écritures ont-elles été écrites selon Romains 15:4 ?", ["Pour notre instruction", "Pour divertir seulement", "Pour confondre", "Pour être ignorées"], 0, "La Bible enseigne et guide."),
  q("Romains 15:4 dit que les Écritures nous donnent…", ["L'espérance et l'endurance", "La peur", "L'orgueil", "L'indifférence"], 0, "Les récits bibliques fortifient notre espérance."),
  q("« Tout ce qui a été écrit auparavant » désigne surtout…", ["Les Écritures hébraïques", "Les romans modernes", "Les journaux", "Les mythes païens"], 0, "Paul parle des Écritures hébraïques disponibles alors."),
  q("Comment tirer profit de Romains 15:4 ?", ["Étudier la Bible pour en recevoir l'instruction", "Ne jamais lire", "Lire sans réfléchir", "Rejeter l'Ancien Testament"], 0, "L'étude régulière nourrit notre foi.")),

e("Car là où deux ou trois se réunissent en mon nom, je suis au milieu d'eux.", "Matthieu 18:20",
  "Jésus promet sa présence spirituelle quand ses disciples se réunissent en son nom. Cela encourage la fréquentation et la prière en groupe.",
  q("Quand Jésus est-il « au milieu » de ses disciples ?", ["Quand deux ou trois se réunissent en son nom", "Quand ils sont seuls", "Quand ils se disputent", "Quand ils l'ignorent"], 0, "Jésus bénit les réunions en son nom."),
  q("« En mon nom » signifie…", ["Conformément à sa volonté et son autorité", "En utilisant son nom comme formule magique", "Sans le respecter", "En secret"], 0, "Se réunir en son nom, c'est agir selon sa volonté."),
  q("Matthieu 18:20 encourage surtout…", ["La fréquentation et la prière en groupe", "L'isolement", "La compétition", "L'indifférence"], 0, "Les réunions chrétiennes ont la bénédiction de Jésus."),
  q("Ce verset se trouve dans un contexte sur…", ["La discipline et le pardon dans la congrégation", "La guerre", "La construction", "Le commerce"], 0, "Matthieu 18 traite des relations entre disciples.")),

e("Car Dieu a tant aimé le monde qu'il a donné son Fils unique, afin que quiconque croit en lui ne périsse pas.", "Jean 3:16",
  "Jean résume l'amour de Dieu : il a donné son Fils pour que nous ayons la vie. Cette promesse révèle la profondeur de l'amour divin.",
  q("Qu'a fait Dieu par amour pour le monde en Jean 3:16 ?", ["Il a donné son Fils unique", "Il a abandonné le monde", "Il a détruit l'humanité", "Il a ignoré nos besoins"], 0, "Le don du Fils est la preuve suprême de l'amour de Dieu."),
  q("Quel bénéfice est promis à « quiconque croit » ?", ["Ne pas périr mais avoir la vie éternelle", "La richesse terrestre", "Le pouvoir politique", "L'immortalité immédiate du corps"], 0, "La foi en Jésus ouvre la voie à la vie éternelle."),
  q("Jean 3:16 montre que l'initiative de l'amour vient de…", ["Dieu", "L'homme seul", "Les anges", "Le hasard"], 0, "Dieu a aimé le monde en premier."),
  q("« Son Fils unique » désigne…", ["Jésus Christ", "Moïse", "David", "Jean-Baptiste"], 0, "Jésus est le Fils unique que Dieu a donné.")),

e("Heureux ceux qui ont faim et soif de la justice, car ils seront rassasiés.", "Matthieu 5:6",
  "Jésus déclare heureux ceux qui désirent ardemment la justice. Ce désir sincère sera satisfait par Jéhovah.",
  q("Qui sont « heureux » selon Matthieu 5:6 ?", ["Ceux qui ont faim et soif de la justice", "Ceux qui ignorent la justice", "Ceux qui rejettent Dieu", "Ceux qui cherchent la richesse"], 0, "Le désir ardent de la justice est béni."),
  q("« Ils seront rassasiés » promet…", ["Que leur désir de justice sera comblé", "Qu'ils ne mangeront jamais", "Qu'ils resteront insatisfaits", "Qu'ils seront punis"], 0, "Jéhovah satisfait ceux qui recherchent la justice."),
  q("Matthieu 5:6 fait partie de…", ["Les Béatitudes du Sermon sur la montagne", "La dernière Cène", "La crucifixion", "La résurrection"], 0, "C'est la quatrième Béatitude."),
  q("Avoir « faim et soif de la justice » implique…", ["Désirer sincèrement faire la volonté de Dieu", "Chercher la vengeance", "Ignorer la Bible", "Ne penser qu'à soi"], 0, "C'est un désir profond d'alignement avec Jéhovah.")),

e("Car nous marchons par la foi, et non par la vue.", "2 Corinthiens 5:7",
  "Paul rappelle que la vie chrétienne repose sur la confiance en Jéhovah plutôt que sur ce que nos yeux voient. La foi guide nos pas.",
  q("Par quoi marchons-nous selon 2 Corinthiens 5:7 ?", ["Par la foi, non par la vue", "Par la vue seule", "Par la peur", "Par le hasard"], 0, "La foi, pas les apparences, guide le chrétien."),
  q("« Marcher par la foi » signifie…", ["Faire confiance à Jéhovah malgré l'invisible", "Agir sans réfléchir", "Nier la réalité", "Ignorer la Bible"], 0, "Nous croyons aux promesses de Jéhovah."),
  q("2 Corinthiens 5:7 contraste la foi avec…", ["La vue (ce que nos yeux perçoivent)", "La prière", "L'amour", "L'espérance"], 0, "Les apparences peuvent tromper ; la foi non."),
  q("Paul écrit cela alors qu'il parle de…", ["Notre condition terrestre et la résurrection", "La cuisine", "La guerre", "Le commerce"], 0, "Paul encourage malgré les épreuves visibles.")),

e("Car l'amour du Christ nous contraint, parce que nous avons jugé qu'un seul est mort pour tous.", "2 Corinthiens 5:14",
  "Paul explique que l'amour de Christ le pousse à agir : Jésus est mort pour tous, ce qui change notre perspective sur la vie.",
  q("Qu'est-ce qui « contraint » Paul en 2 Corinthiens 5:14 ?", ["L'amour du Christ", "La peur des hommes", "La richesse", "L'orgueil"], 0, "L'amour de Christ motive son service."),
  q("« Un seul est mort pour tous » désigne…", ["Jésus Christ", "Moïse", "Paul", "Pierre"], 0, "Jésus est mort pour l'humanité."),
  q("La mort de Jésus pour tous implique que…", ["Ceux qui vivent ne devraient plus vivre pour eux-mêmes", "Chacun vit pour soi", "La mort n'a pas d'importance", "On peut ignorer Christ"], 0, "Paul en tire une conclusion en v. 15."),
  q("2 Corinthiens 5:14-15 montre que l'amour de Christ pousse à…", ["Vivre pour celui qui est mort et ressuscité", "Vivre égoïstement", "Abandonner le service", "Nier la résurrection"], 0, "Nous servons celui qui nous a rachetés.")),

e("Car rien ne pourra nous séparer de l'amour de Dieu manifesté par Christ Jésus notre Seigneur.", "Romains 8:39",
  "Paul conclut avec assurance : aucune force ne peut nous arracher à l'amour de Dieu. Cette certitude fortifie notre espérance.",
  q("Que ne peut-on pas séparer de l'amour de Dieu selon Romains 8:39 ?", ["Les serviteurs fidèles de Dieu", "Les anges seulement", "Personne", "Les animaux"], 0, "Rien ne peut nous séparer de son amour."),
  q("Romains 8:38-39 énumère des forces comme la mort, la vie, les anges…", ["Pour montrer qu'aucune ne peut nous séparer de l'amour de Dieu", "Pour nous effrayer", "Pour nier l'amour de Dieu", "Pour glorifier le mal"], 0, "Paul liste les puissances pour affirmer la victoire de l'amour."),
  q("L'amour de Dieu est « manifesté par » qui ?", ["Christ Jésus notre Seigneur", "Moïse", "César", "Les prophètes seuls"], 0, "Jésus révèle l'amour de Dieu."),
  q("Romains 8:39 apporte surtout…", ["Une assurance et une consolation", "Une condamnation", "Une confusion", "Un rejet"], 0, "Paul rassure les chrétiens de l'amour inébranlable de Dieu.")),
]
