#!/usr/bin/env python3
"""Generate verse_seed_part3.py with entries 112-342."""
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "scripts/verse_seed_part3.py")

POOL = [
("Matthieu 6:9", "Notre Père qui es aux cieux, que ton nom soit sanctifié.", "Jésus enseigne à adresser la prière au Père céleste avec révérence pour son nom.", "Jésus", "que ton nom soit sanctifié", "Sanctifier le nom de Jéhovah en prière"),
("Matthieu 6:14", "Si vous pardonnez aux hommes leurs fautes, votre Père céleste vous pardonnera aussi.", "Le pardon que nous accordons est lié au pardon que nous recevons.", "Jésus", "pardonnez aux hommes", "Pardonner aux autres"),
("Matthieu 6:19", "Ne stockez pas pour vous des richesses sur la terre.", "Jésus met en garde contre l'attachement aux richesses matérielles.", "Jésus", "Ne stockez pas des richesses", "Fixer des trésors spirituels"),
("Matthieu 6:21", "Car là où est votre trésor, là votre cœur sera aussi.", "Nos priorités révèlent où est notre cœur.", "Jésus", "là votre cœur sera", "Examiner où est notre trésor"),
("Matthieu 6:24", "Personne ne peut servir deux maîtres… Vous ne pouvez pas servir Dieu et l'argent.", "Jésus exige une loyauté exclusive envers Jéhovah.", "Jésus", "servir deux maîtres", "Servir Jéhovah exclusivement"),
("Matthieu 6:34", "Ne vous inquiétez pas du lendemain, car le lendemain s'inquiétera de lui-même.", "Jésus déconseille l'inquiétude excessive pour l'avenir.", "Jésus", "Ne vous inquiétez pas du lendemain", "Vivre un jour à la fois"),
("Matthieu 7:1", "Cessez de juger, pour ne pas être jugés.", "Jésus met en garde contre un jugement harsh envers autrui.", "Jésus", "Cessez de juger", "Éviter un jugement harsh"),
("Matthieu 7:7", "Continuez à demander, et on vous donnera ; continuez à chercher, et vous trouverez.", "Jésus encourage la persévérance dans la prière.", "Jésus", "Continuez à demander", "Persévérer dans la prière"),
("Matthieu 7:13", "Entrez par la porte étroite, car spacieuse est la porte et large le chemin qui mène à la destruction.", "Jésus met en garde : le chemin vers la vie est étroit et exigeant.", "Jésus", "la porte étroite", "Choisir le chemin étroit"),
("Matthieu 7:21", "Ceux qui me disent : « Seigneur, Seigneur », n'entreront pas dans le royaume des cieux, mais celui qui fait la volonté de mon Père.", "Faire la volonté de Dieu compte plus que les paroles.", "Jésus", "fait la volonté de mon Père", "Faire la volonté du Père"),
("Matthieu 10:39", "Celui qui a trouvé sa vie la perdra, et celui qui a perdu sa vie à cause de moi la trouvera.", "Mettre Jésus en premier transforme notre vie.", "Jésus", "perdu sa vie à cause de moi", "Mettre Jésus en premier"),
("Matthieu 11:28", "Venez à moi, vous tous qui peinez et vous sentez chargés, et je vous donnerai du réconfort.", "Jésus invite les fatigués à trouver du réconfort en lui.", "Jésus", "je vous donnerai du réconfort", "Chercher réconfort en Jésus"),
("Matthieu 11:29", "Prenez mon joug sur vous et apprenez de moi, car je suis doux et humble de cœur.", "Jésus est modèle de douceur et d'humilité.", "Jésus", "doux et humble de cœur", "Imiter la douceur de Jésus"),
("Matthieu 16:26", "Que servirait-il à un homme de gagner le monde entier s'il perdait sa vie ?", "Les gains matériels ne valent pas la vie éternelle.", "Jésus", "perdait sa vie", "Prioriser la vie éternelle"),
("Matthieu 18:15", "Si ton frère commet un péché, va le reprendre seul à seul.", "Jésus enseigne une démarche de réconciliation progressive.", "Jésus", "va le reprendre seul à seul", "Chercher à réconcilier"),
("Matthieu 19:26", "Pour les hommes, c'est impossible, mais pour Dieu, tout est possible.", "Jéhovah peut accomplir ce qui dépasse nos forces.", "Jésus", "pour Dieu, tout est possible", "Confier l'impossible à Jéhovah"),
("Matthieu 22:37", "Tu aimeras Jéhovah ton Dieu de tout ton cœur, de toute ton âme et de toute ta pensée.", "Le premier et grand commandement est l'amour pour Jéhovah.", "Jésus", "Tu aimeras Jéhovah", "Aimer Jéhovah de tout son être"),
("Matthieu 22:39", "Tu aimeras ton prochain comme toi-même.", "Le second commandement est l'amour du prochain.", "Jésus", "Tu aimeras ton prochain", "Aimer son prochain"),
("Matthieu 28:19", "Allez donc, faites des disciples de toutes les nations, les baptisant.", "Jésus confie la mission de faire des disciples.", "Jésus", "faites des disciples", "Participer à la prédication"),
("Matthieu 28:20", "Et voici, je suis avec vous tous les jours, jusqu'à la fin du système.", "Jésus promet sa présence jusqu'à la fin.", "Jésus", "je suis avec vous", "Compter sur la présence de Jésus"),
("Marc 10:45", "Le Fils de l'homme est venu, non pas pour être servi, mais pour servir.", "Jésus est modèle de service désintéressé.", "Jésus", "pour servir", "Servir les autres"),
("Marc 12:30", "Tu aimeras Jéhovah ton Dieu de tout ton cœur, de toute ton âme, de toute ta pensée et de toute ta force.", "L'amour pour Jéhovah engage tout notre être.", "Jésus", "de toute ta force", "Aimer Jéhovah de toutes ses forces"),
("Luc 1:37", "Car aucune parole de Dieu ne manquera de s'accomplir.", "Les promesses de Jéhovah s'accomplissent toujours.", "L'ange Gabriel", "ne manquera pas de s'accomplir", "Croire aux promesses de Jéhovah"),
("Luc 2:10", "Ne craignez pas, car voici, je vous annonce une bonne nouvelle.", "L'ange annonce la naissance du Sauveur.", "L'ange", "bonne nouvelle", "Partager la bonne nouvelle"),
("Luc 6:31", "Et comme vous voulez que les hommes vous traitent, traitez-les de la même manière.", "La règle d'or enseignée par Jésus.", "Jésus", "traitez-les de la même manière", "Traiter autrui avec bienveillance"),
("Luc 6:35", "Aimez vos ennemis, faites du bien et prêtez sans rien attendre en retour.", "Jésus exige un amour extraordinaire.", "Jésus", "Aimez vos ennemis", "Aimer ses ennemis"),
("Luc 6:38", "Donnez, et on vous donnera.", "La générosité est récompensée par Jéhovah.", "Jésus", "Donnez, et on vous donnera", "Pratiquer la générosité"),
("Luc 10:27", "Tu aimeras Jéhovah ton Dieu… et ton prochain comme toi-même.", "Résumé de la loi par le scribe.", "Jésus", "ton prochain comme toi-même", "Aimer Jéhovah et le prochain"),
("Luc 11:9", "Demandez, et on vous donnera ; cherchez, et vous trouverez ; frappez, et on vous ouvrira.", "Jésus encourage la persévérance dans la prière.", "Jésus", "Demandez, et on vous donnera", "Persévérer dans la prière"),
("Luc 12:15", "Prenez garde et restez en garde contre toute forme de convoitise.", "Jésus met en garde contre la convoitise.", "Jésus", "contre toute forme de convoitise", "Se garder de la convoitise"),
("Luc 12:34", "Car là où est votre trésor, là votre cœur sera aussi.", "Nos priorités révèlent notre cœur.", "Jésus", "là votre cœur sera", "Examiner nos priorités"),
("Luc 15:7", "Il y aura plus de joie au ciel pour un pécheur qui se repent.", "Jéhovah se réjouit quand un pécheur revient.", "Jésus", "plus de joie au ciel", "Se réjouir du repentir"),
("Luc 17:32", "Souvenez-vous de la femme de Lot.", "Jésus met en garde contre l'attachement au passé.", "Jésus", "femme de Lot", "Ne pas regarder en arrière"),
("Luc 18:1", "Il leur dit toujours une parabole pour montrer qu'ils doivent prier continuellement.", "Jésus enseigne la persévérance dans la prière.", "Jésus", "prier continuellement", "Prier sans relâche"),
("Luc 21:19", "En restant fermes, vous acquérez vos âmes.", "La persévérance sauvegarde notre vie spirituelle.", "Jésus", "En restant fermes", "Rester ferme dans l'épreuve"),
("Jean 1:1", "Au commencement était la Parole, et la Parole était avec Dieu.", "Jean présente Jésus comme la Parole divine.", "Jean", "Au commencement était la Parole", "Reconnaître Jésus comme la Parole"),
("Jean 1:14", "La Parole est devenue chair et a habité parmi nous.", "Jésus est venu sur terre comme un homme.", "Jean", "est devenue chair", "Apprécier l'incarnation de Jésus"),
("Jean 3:3", "Si un homme ne naît de nouveau, il ne peut pas voir le royaume de Dieu.", "Jésus enseigne la nécessité d'une naissance spirituelle.", "Jésus", "naît de nouveau", "Chercher une vie spirituelle renouvelée"),
("Jean 3:17", "Car Dieu a envoyé son Fils dans le monde, non pas pour juger le monde, mais pour sauver le monde.", "Jésus est venu pour sauver, non pour condamner.", "Jésus", "pour sauver le monde", "Partager le message de salut"),
("Jean 4:24", "Dieu est un esprit, et ceux qui l'adorent doivent l'adorer avec esprit et vérité.", "L'adoration véritable est spirituelle et sincère.", "Jésus", "esprit et vérité", "Adorer avec sincérité"),
("Jean 6:44", "Nul ne peut venir à moi, à moins que le Père ne l'attire.", "Jéhovah attire ceux qui viennent à Jésus.", "Jésus", "le Père ne l'attire", "Répondre à l'appel de Jéhovah"),
("Jean 8:12", "Je suis la lumière du monde. Celui qui me suit ne marchera pas dans les ténèbres.", "Jésus éclaire le chemin de la vie.", "Jésus", "lumière du monde", "Suivre Jésus comme lumière"),
("Jean 8:32", "Vous connaîtrez la vérité, et la vérité vous rendra libres.", "La vérité de Jéhovah libère.", "Jésus", "la vérité vous rendra libres", "Chercher la vérité biblique"),
("Jean 10:10", "Le voleur ne vient que pour voler, tuer et détruire. Moi, je suis venu afin qu'ils aient la vie.", "Jésus offre la vie en abondance.", "Jésus", "afin qu'ils aient la vie", "Accepter la vie que Jésus offre"),
("Jean 10:14", "Je suis le bon berger ; je connais mes brebis et mes brebis me connaissent.", "Jésus se compare au berger qui connaît son troupeau.", "Jésus", "bon berger", "Connaître Jésus personnellement"),
("Jean 11:25", "Je suis la résurrection et la vie. Celui qui croit en moi vivra.", "Jésus promet la vie éternelle à ceux qui croient.", "Jésus", "résurrection et la vie", "Croire en Jésus pour la vie"),
("Jean 13:35", "Par ceci tous sauront que vous êtes mes disciples : si vous avez de l'amour les uns pour les autres.", "L'amour fraternel identifie les disciples.", "Jésus", "amour les uns pour les autres", "Manifester l'amour fraternel"),
("Jean 14:1", "Que votre cœur ne se trouble pas. Ayez foi en Dieu et ayez foi en moi.", "Jésus rassure ses disciples avant sa mort.", "Jésus", "Ayez foi en Dieu", "Avoir foi en Jésus et en Jéhovah"),
("Jean 14:6", "Je suis le chemin, la vérité et la vie. Personne ne vient au Père que par moi.", "Jésus est le seul chemin vers Jéhovah.", "Jésus", "le chemin, la vérité et la vie", "Suivre Jésus comme chemin"),
("Jean 14:15", "Si vous m'aimez, vous obéirez à mes commandements.", "L'amour pour Jésus se manifeste par l'obéissance.", "Jésus", "obéirez à mes commandements", "Obéir par amour pour Jésus"),
("Jean 15:5", "Je suis le cep, vous êtes les branches. Celui qui reste en union avec moi porte beaucoup de fruit.", "Rester unis à Jésus produit des fruits spirituels.", "Jésus", "reste en union avec moi", "Rester unis à Jésus"),
("Jean 15:13", "Personne n'a un amour plus grand que celui-ci : qu'un homme donne sa vie pour ses amis.", "Jésus est le modèle suprême de l'amour sacrificiel.", "Jésus", "donne sa vie pour ses amis", "Imiter l'amour sacrificiel"),
("Jean 16:33", "Dans le monde, vous aurez des tribulations. Mais prenez courage ! J'ai vaincu le monde.", "Jésus prépare ses disciples aux épreuves.", "Jésus", "J'ai vaincu le monde", "Prendre courage en Jésus"),
("Jean 17:3", "Cette vie éternelle, c'est qu'ils te connaissent, toi, le seul vrai Dieu, et celui que tu as envoyé, Jésus Christ.", "La vie éternelle consiste à connaître Jéhovah et Jésus.", "Jésus", "qu'ils te connaissent", "Connaître Jéhovah et Jésus"),
("Jean 20:29", "Heureux ceux qui croient sans avoir vu !", "Jésus bénit ceux qui croient par la foi.", "Jésus", "croient sans avoir vu", "Croire sans avoir vu"),
("Actes 1:8", "Vous serez mes témoins… jusqu'aux extrémités de la terre.", "Jésus confie la mission de témoignage.", "Jésus", "mes témoins", "Être témoin de Jésus"),
("Actes 2:38", "Repentez-vous, et que chacun de vous soit baptisé.", "Pierre exhorte au repentir et au baptême.", "Pierre", "Repentez-vous", "Se repentir sincèrement"),
("Actes 4:12", "Il n'y a de salut en aucun autre, car il n'y a sous le ciel aucun autre nom par lequel nous devions être sauvés.", "Le salut est uniquement par Jésus.", "Pierre", "aucun autre nom", "Reconnaître Jésus comme seul Sauveur"),
("Actes 5:29", "Il faut obéir à Dieu comme autorité suprême plutôt qu'aux hommes.", "Obéir à Jéhovah avant les hommes.", "Pierre", "obéir à Dieu", "Obéir à Jéhovah en priorité"),
("Actes 17:11", "Ils étudiaient les Écritures chaque jour pour voir si ces choses étaient vraies.", "Les Béréens vérifiaient tout par les Écritures.", "Luc", "étudiaient les Écritures", "Vérifier l'enseignement par la Bible"),
("Actes 20:35", "Il y a plus de bonheur à donner qu'à recevoir.", "Jésus enseigne la joie de donner.", "Paul", "plus de bonheur à donner", "Trouver joie à donner"),
("Romains 1:16", "Car je n'ai pas honte de la bonne nouvelle ; c'est, en effet, la puissance de Dieu.", "Paul n'a pas honte de prêcher l'Évangile.", "Paul", "puissance de Dieu", "Ne pas avoir honte de la bonne nouvelle"),
("Romains 3:23", "Car tous ont péché et n'atteignent pas la gloire de Dieu.", "Tous les humains ont besoin du salut.", "Paul", "tous ont péché", "Reconnaître son besoin de salut"),
("Romains 5:8", "Dieu prouve son amour pour nous en ce que, alors que nous étions encore des pécheurs, Christ est mort pour nous.", "L'amour de Dieu est prouvé par la mort de Christ.", "Paul", "Christ est mort pour nous", "Apprécier l'amour de Dieu"),
("Romains 6:23", "Car le salaire du péché, c'est la mort, mais le don gratuit de Dieu, c'est la vie éternelle.", "Dieu offre la vie éternelle gratuitement.", "Paul", "don gratuit de Dieu", "Accepter le don de la vie éternelle"),
("Romains 8:28", "Nous savons que Dieu fait concourir toutes choses au bien de ceux qui aiment Dieu.", "Jéhovah arrange les circonstances pour le bien de ses serviteurs.", "Paul", "concourir toutes choses au bien", "Confier ses circonstances à Jéhovah"),
("Romains 10:13", "Car quiconque appelle sur le nom de Jéhovah sera sauvé.", "Appeler sur le nom de Jéhovah ouvre le salut.", "Paul", "appelle sur le nom de Jéhovah", "Appeler sur le nom de Jéhovah"),
("Romains 12:1", "Je vous exhorte, frères, à offrir vos corps en sacrifice vivant, saint et acceptable à Dieu.", "Paul exhorte à consacrer sa vie à Jéhovah.", "Paul", "sacrifice vivant", "Consacrer sa vie à Jéhovah"),
("Romains 12:2", "Ne vous conformez pas à ce système, mais transformez-vous.", "Ne pas imiter le monde ; se transformer par l'esprit.", "Paul", "Ne vous conformez pas", "Ne pas imiter le monde"),
("Romains 12:10", "Aimez-vous les uns les autres avec affection fraternelle.", "L'affection fraternelle unit la congrégation.", "Paul", "affection fraternelle", "Aimer avec affection fraternelle"),
("Romains 12:12", "Réjouissez-vous en espérance. Supportez la détresse avec persévérance. Persistez dans la prière.", "Trois attitudes essentielles : joie, endurance, prière.", "Paul", "Persistez dans la prière", "Persister dans la prière"),
("Romains 12:17", "Ne rendez à personne le mal pour le mal.", "Ne pas riposter au mal par le mal.", "Paul", "Ne rendez pas le mal pour le mal", "Répondre au mal par le bien"),
("Romains 12:21", "Ne te laisse pas vaincre par le mal, mais continue à vaincre le mal par le bien.", "Vaincre le mal par le bien est la voie chrétienne.", "Paul", "vaincre le mal par le bien", "Répondre au mal par le bien"),
("Romains 14:12", "Ainsi, chacun de nous rendra compte à Dieu pour lui-même.", "Chacun est responsable devant Jéhovah.", "Paul", "rendra compte à Dieu", "Agir sachant qu'on rendra compte"),
("1 Corinthiens 10:13", "Dieu est fidèle, et il ne permettra pas que vous soyez mis à l'épreuve au-delà de vos capacités.", "Jéhovah limite nos épreuves à ce que nous pouvons supporter.", "Paul", "au-delà de vos capacités", "Confier ses épreuves à Jéhovah"),
("1 Corinthiens 13:4", "L'amour est patient et bienveillant.", "Paul décrit les qualités de l'amour véritable.", "Paul", "patient et bienveillant", "Faire preuve de patience et bonté"),
("1 Corinthiens 13:8", "L'amour ne disparaît jamais.", "L'amour est permanent, contrairement aux dons temporaires.", "Paul", "ne disparaît jamais", "Cultiver un amour durable"),
("1 Corinthiens 13:13", "Maintenant, cependant, restent la foi, l'espérance, l'amour, ces trois choses ; mais la plus grande de toutes, c'est l'amour.", "L'amour surpasse la foi et l'espérance.", "Paul", "la plus grande, c'est l'amour", "Placer l'amour au premier plan"),
("1 Corinthiens 15:58", "Soyez fermes, inébranlables, et continuez à vous appliquer de plus en plus à l'œuvre du Seigneur.", "Paul encourage à persévérer dans le service.", "Paul", "continuez à vous appliquer", "Persévérer dans le service"),
("2 Corinthiens 4:16", "Nous ne nous rendons pas, mais même si notre homme extérieur se dégrade, notre homme intérieur se renouvelle chaque jour.", "L'homme intérieur se renouvelle malgré le vieillissement.", "Paul", "homme intérieur se renouvelle", "Nourrir sa vie intérieure"),
("2 Corinthiens 9:7", "Que chacun donne comme il l'a résolu dans son cœur, sans regret ni contrainte.", "Donner avec joie et spontanéité.", "Paul", "sans regret ni contrainte", "Donner avec joie"),
("Galates 5:22", "Le fruit de l'esprit est l'amour, la joie, la paix, la patience, la bonté, la bonté d'âme, la foi, la douceur, la maîtrise de soi.", "L'esprit produit des qualités remarquables.", "Paul", "fruit de l'esprit", "Cultiver le fruit de l'esprit"),
("Galates 6:7", "Ne vous y trompez pas : on ne se moque pas de Dieu. Ce qu'un homme sème, il le moissonnera.", "Nos actions ont des conséquences.", "Paul", "il le moissonnera", "Semer des actions justes"),
("Galates 6:9", "Ne nous lassons pas de faire le bien, car nous moissonnerons au moment voulu si nous ne faiblissons pas.", "Persévérer dans le bien sera récompensé.", "Paul", "Ne nous lassons pas", "Persévérer dans le bien"),
("Éphésiens 2:10", "Nous sommes en effet son ouvrage, créés en union avec Christ Jésus pour de bonnes œuvres.", "Nous sommes créés pour de bonnes œuvres.", "Paul", "de bonnes œuvres", "Pratiquer de bonnes œuvres"),
("Éphésiens 4:25", "C'est pourquoi, renoncez au mensonge et dites la vérité chacun à son prochain.", "L'honnêteté caractérise les chrétiens.", "Paul", "dites la vérité", "Pratiquer l'honnêteté"),
("Éphésiens 4:29", "Que toute parole malsaine ne sorte pas de votre bouche.", "Surveiller nos paroles.", "Paul", "parole malsaine", "Contrôler ses paroles"),
("Éphésiens 4:32", "Devenez bons les uns envers les autres, compatissants, pardonnant.", "Pardonner comme Jéhovah nous a pardonné.", "Paul", "pardonnant", "Pardonner aux autres"),
("Éphésiens 5:25", "Les maris, aimez vos femmes, tout comme le Christ a aimé la congrégation.", "Les maris imitent l'amour de Christ.", "Paul", "aimez vos femmes", "Aimer sa femme"),
("Éphésiens 6:1", "Enfants, soyez obéissants à vos parents en union avec le Seigneur.", "L'obéissance aux parents plaît à Jéhovah.", "Paul", "obéissants à vos parents", "Obéir à ses parents"),
("Éphésiens 6:4", "Pères, n'exaspérez pas vos enfants, mais continuez à les élever dans la discipline et les remontrances de Jéhovah.", "Élever les enfants avec patience et discipline.", "Paul", "discipline et remontrances de Jéhovah", "Élever ses enfants selon Jéhovah"),
("Philippiens 1:21", "Car pour moi, le fait de vivre, c'est Christ.", "Paul vit entièrement pour Christ.", "Paul", "vivre, c'est Christ", "Vivre pour Christ"),
("Philippiens 2:3", "Ne faites rien par esprit de rivalité ou par orgueil.", "L'humilité doit guider nos actions.", "Paul", "par orgueil", "Agir avec humilité"),
("Philippiens 2:4", "Que chacun de vous regarde, non pas seulement ses propres intérêts, mais aussi ceux des autres.", "S'intéresser aux besoins d'autrui.", "Paul", "intérêts des autres", "Se soucier des autres"),
("Philippiens 2:5", "Ayez en vous la même attitude que Christ Jésus.", "Imiter l'attitude de Jésus.", "Paul", "même attitude que Christ", "Imiter l'attitude de Jésus"),
("Philippiens 4:8", "Tout ce qui est vrai, tout ce qui est sérieux, tout ce qui est juste… continuez à penser à ces choses.", "Fixer son mental sur ce qui est positif.", "Paul", "continuez à penser à ces choses", "Penser à ce qui est bon"),
("Philippiens 4:13", "Je peux tout par celui qui me donne de la force.", "Paul puise sa force en Christ.", "Paul", "celui qui me donne de la force", "Chercher la force en Christ"),
("Colossiens 3:9", "Ne mentez pas les uns aux autres.", "L'honnêteté entre frères est exigée.", "Paul", "Ne mentez pas", "Pratiquer l'honnêteté"),
("Colossiens 3:13", "Continuez à vous pardonner mutuellement.", "Le pardon mutuel maintient l'unité.", "Paul", "pardonner mutuellement", "Pardonner à ses frères"),
("Colossiens 3:23", "Tout ce que vous faites, faites-le de bon cœur, comme pour Jéhovah et non pour des hommes.", "Travailler comme pour Jéhovah.", "Paul", "comme pour Jéhovah", "Travailler pour Jéhovah"),
("1 Thessaloniciens 4:11", "Faites en sorte de vous occuper de vos propres affaires et de travailler de vos mains.", "Vivre tranquillement et travailler honnêtement.", "Paul", "travailler de vos mains", "Travailler honnêtement"),
("1 Thessaloniciens 5:11", "Continuez à vous encourager les uns les autres et à vous bâtir les uns les autres.", "L'encouragement mutuel fortifie la congrégation.", "Paul", "vous encourager les uns les autres", "Encourager ses frères"),
("1 Thessaloniciens 5:14", "Supportez-vous les uns les autres.", "La patience mutuelle est essentielle.", "Paul", "Supportez-vous", "Supporter ses frères"),
("2 Thessaloniciens 3:10", "Si quelqu'un ne veut pas travailler, qu'il ne mange pas non plus.", "Le travail honnête est une responsabilité.", "Paul", "ne veut pas travailler", "Travailler avec diligence"),
("1 Timothée 2:5", "Car il y a un seul Dieu et un seul médiateur entre Dieu et les hommes, un homme, Christ Jésus.", "Jésus est le seul médiateur.", "Paul", "un seul médiateur", "Reconnaître Jésus comme médiateur"),
("1 Timothée 4:12", "Que personne ne fasse fi de ta jeunesse. Mais deviens un exemple pour les fidèles.", "La jeunesse n'empêche pas d'être un modèle.", "Paul", "exemple pour les fidèles", "Être un exemple malgré son âge"),
("1 Timothée 6:10", "L'amour de l'argent est une racine de toutes sortes de choses mauvaises.", "L'amour de l'argent mène au mal.", "Paul", "amour de l'argent", "Se garder de l'amour de l'argent"),
("2 Timothée 1:7", "Car Dieu ne nous a pas donné un esprit de lâcheté, mais de puissance, d'amour et de sagesse.", "Jéhovah donne puissance, amour et sagesse.", "Paul", "esprit de puissance", "Utiliser la force que Jéhovah donne"),
("2 Timothée 3:16", "Toute Écriture est inspirée de Dieu et profitable pour enseigner.", "La Bible est inspirée et utile.", "Paul", "inspirée de Dieu", "Étudier toute l'Écriture"),
("Tite 2:7", "Montre-toi toi-même un exemple de bonnes œuvres en toute chose.", "Le comportement doit être un modèle.", "Paul", "exemple de bonnes œuvres", "Être un exemple"),
("Hébreux 10:24", "Continuons à nous inciter les uns les autres à l'amour et à de bonnes œuvres.", "S'inciter mutuellement à l'amour.", "Paul", "inciter les uns les autres", "Encourager à l'amour"),
("Hébreux 10:25", "Ne abandonnons pas notre assemblée.", "La fréquentation est vitale.", "Paul", "notre assemblée", "Fréquenter l'assemblée"),
("Hébreux 11:1", "La foi est la preuve évidente de choses qu'on ne voit pas.", "La foi rend réelles les choses invisibles.", "Paul", "preuve évidente", "Exercer la foi"),
("Hébreux 11:6", "Sans la foi, il est impossible de lui plaire.", "La foi est indispensable pour plaire à Jéhovah.", "Paul", "impossible de lui plaire", "Cultiver la foi"),
("Hébreux 12:1", "Courons avec endurance la course qui nous est imposée.", "La vie chrétienne demande endurance.", "Paul", "avec endurance", "Courir avec endurance"),
("Hébreux 13:5", "Ne aimez pas l'argent ; soyez content de ce que vous avez.", "Se contenter de ce que Jéhovah fournit.", "Paul", "soyez content", "Se contenter"),
("Hébreux 13:16", "Ne oubliez pas de faire le bien et de partager avec d'autres.", "Le bien et le partage plaisent à Jéhovah.", "Paul", "faire le bien", "Partager avec d'autres"),
("Jacques 1:5", "Si l'un de vous manque de sagesse, qu'il la demande à Dieu.", "Jéhovah donne la sagesse généreusement.", "Jacques", "demander à Dieu", "Demander la sagesse à Jéhovah"),
("Jacques 1:17", "Tout don parfait et tout prés qui descend d'en haut vient du Père des lumières célestes.", "Tout bien vient de Jéhovah.", "Jacques", "vient du Père", "Reconnaître Jéhovah comme source de bien"),
("Jacques 1:19", "Que tout homme soit prompt à écouter, lent à parler, lent à la colère.", "Maîtriser ses paroles et sa colère.", "Jacques", "prompt à écouter", "Écouter avant de parler"),
("Jacques 1:22", "Mettez la parole en pratique, et ne vous limitez pas à l'écouter.", "Appliquer la Parole, pas seulement l'entendre.", "Jacques", "Mettez la parole en pratique", "Appliquer la Bible"),
("Jacques 2:26", "De même, la foi sans les œuvres est morte.", "La vraie foi produit des actions.", "Jacques", "foi sans les œuvres", "Manifester sa foi par des actes"),
("Jacques 4:7", "Soumettez-vous donc à Dieu, mais résistez au diable.", "Soumission à Jéhovah et résistance au mal.", "Jacques", "Soumettez-vous à Dieu", "Se soumettre à Jéhovah"),
("Jacques 4:8", "Approchez-vous de Dieu, et il s'approchera de vous.", "S'approcher de Jéhovah attire sa proximité.", "Jacques", "il s'approchera de vous", "S'approcher de Jéhovah"),
("Jacques 5:16", "Une prière fervente du juste a une grande efficacité.", "La prière fervente est puissante.", "Jacques", "prière fervente", "Prier avec ferveur"),
("1 Pierre 2:9", "Vous êtes une race choisie, un prêtrise royale, une nation sainte.", "Les chrétiens ont un statut privilégié.", "Pierre", "race choisie", "Vivre dignement de son appel"),
("1 Pierre 3:15", "Sanctifiez le Christ comme Seigneur dans vos cœurs, toujours prêts à présenter une défense.", "Être prêt à défendre sa foi.", "Pierre", "prêts à présenter une défense", "Se préparer à défendre sa foi"),
("1 Pierre 4:8", "Par-dessus toutes choses, ayez un amour intense les uns pour les autres, car l'amour couvre une multitude de péchés.", "L'amour intense couvre les fautes et préserve l'unité.", "Pierre", "l'amour couvre une multitude de péchés", "Aimer intensément pour préserver l'unité"),
("1 Pierre 5:6", "Humiliez-vous donc sous la main puissante de Dieu.", "L'humilité devant Jéhovah est exigée.", "Pierre", "Humiliez-vous", "S'humilier devant Jéhovah"),
("1 Pierre 5:7", "Lancez-vous sur lui toute votre inquiétude, car lui prend soin de vous.", "Jéhovah se soucie de nous ; confions-lui nos soucis.", "Pierre", "lui prend soin de vous", "Confier ses inquiétudes à Jéhovah"),
("2 Pierre 3:9", "Jéhovah n'est pas lent concernant sa promesse, comme certains le considèrent lent.", "Jéhovah agit selon son calendrier, pas le nôtre.", "Pierre", "sa promesse", "Patience envers les promesses de Jéhovah"),
("1 Jean 1:9", "Si nous confessons nos péchés, il est fidèle et juste pour nous pardonner.", "Jéhovah pardonne quand nous confessons.", "Jean", "nous pardonner", "Confesser ses péchés"),
("1 Jean 2:17", "Le monde passe, et sa convoitise aussi, mais celui qui fait la volonté de Dieu demeure éternellement.", "Faire la volonté de Dieu assure la vie éternelle.", "Jean", "fait la volonté de Dieu", "Faire la volonté de Jéhovah"),
("1 Jean 3:18", "Petits enfants, n'aimons pas en paroles seulement, mais aussi par des actes.", "L'amour véritable se manifeste par des actes.", "Jean", "par des actes", "Aimer par des actions"),
("1 Jean 4:8", "Dieu est amour.", "L'amour est la qualité essentielle de Jéhovah.", "Jean", "Dieu est amour", "Imiter l'amour de Jéhovah"),
("1 Jean 4:19", "Nous l'aimons, parce qu'il nous a aimés le premier.", "L'amour de Jéhovah précède le nôtre.", "Jean", "il nous a aimés le premier", "Répondre à l'amour de Jéhovah"),
("1 Jean 5:3", "Car l'amour pour Dieu consiste à observer ses commandements.", "Obéir est une preuve d'amour pour Jéhovah.", "Jean", "observer ses commandements", "Obéir par amour"),
("Jude 21", "Gardez-vous dans l'amour de Dieu, en attendant la miséricorde de notre Seigneur Jésus Christ.", "Rester dans l'amour de Dieu en attendant.", "Jude", "Gardez-vous dans l'amour de Dieu", "Rester dans l'amour de Jéhovah"),
("Apocalypse 3:20", "Voici, je me tiens à la porte et je frappe.", "Jésus invite à ouvrir la porte de notre cœur.", "Jésus", "je me tiens à la porte", "Ouvrir son cœur à Jésus"),
("Apocalypse 4:11", "Tu es digne, Jéhovah et Dieu notre, de recevoir la gloire et l'honneur et la puissance.", "Jéhovah seul mérite gloire et honneur.", "Les 24 anciens", "digne de recevoir la gloire", "Donner gloire à Jéhovah"),
("Apocalypse 7:17", "L'agneau qui est au milieu du trône les conduira aux sources d'eaux de la vie.", "Jésus conduira les fidèles à la vie éternelle.", "Jean", "sources d'eaux de la vie", "Suivre l'Agneau"),
("Apocalypse 14:13", "Heureux les morts qui meurent en union avec le Seigneur dès maintenant.", "Mourir fidèle à Jéhovah est un bonheur.", "Jean", "meurent en union avec le Seigneur", "Rester fidèle jusqu'à la mort"),
("Apocalypse 21:3", "Voici la demeure de Dieu avec les humains.", "Jéhovah habitera avec l'humanité.", "Jean", "demeure de Dieu", "Attendre la demeure de Jéhovah"),
("Apocalypse 21:4", "Il essuiera toute larme de leurs yeux, et la mort ne sera plus.", "Jéhovah éliminera la mort et la souffrance.", "Jean", "la mort ne sera plus", "Attendre l'élimination de la mort"),
("Apocalypse 22:12", "Voici, je viens rapidement, et ma récompense est avec moi.", "Jésus promet de venir apporter sa récompense.", "Jésus", "ma récompense est avec moi", "Se préparer au retour de Jésus"),
("Nahum 1:7", "Jéhovah est bon, un refuge au jour de la détresse.", "Jéhovah est bon et un refuge sûr.", "Nahum", "un refuge au jour de la détresse", "Chercher refuge en Jéhovah"),
("Habacuc 2:4", "Le juste, par sa fidélité, vivra.", "La fidélité assure la vie.", "Habacuc", "par sa fidélité, vivra", "Rester fidèle"),
("Sophonie 3:17", "Jéhovah ton Dieu est au milieu de toi. Comme un guerrier, il te sauvera.", "Jéhovah est au milieu de son peuple pour le sauver.", "Sophonie", "il te sauvera", "Compter sur la présence de Jéhovah"),
("Malachie 3:10", "Mettez-moi à l'épreuve, dit Jéhovah des armées, en apportant toutes vos dîmes.", "Jéhovah invite à la générosité en matière de dîmes.", "Jéhovah", "Mettez-moi à l'épreuve", "Faire confiance à Jéhovah"),
("Osée 6:6", "Car j'aime la bonté et non le sacrifice.", "Jéhovah valorise la bonté plus que les rituels.", "Jéhovah", "j'aime la bonté", "Pratiquer la bonté"),
("Joël 2:13", "Revenez à Jéhovah votre Dieu, car il est compatissant et miséricordieux.", "Jéhovah accueille le repentir sincère.", "Joël", "compatissant et miséricordieux", "Revenir à Jéhovah"),
("Amos 5:24", "Que le droit coule comme les eaux, et la justice comme un torrent qui ne tarit jamais.", "Jéhovah exige justice et droiture.", "Amos", "le droit coule comme les eaux", "Pratiquer la justice"),
("Michée 6:8", "On t'a fait connaître, ô homme, ce qui est bon. Exercer la justice, aimer la bonté, marcher humblement avec ton Dieu.", "Résumé de ce que Jéhovah demande.", "Michée", "marcher humblement avec ton Dieu", "Marcher humblement avec Jéhovah"),
("Jonas 2:9", "Le salut appartient à Jéhovah.", "Jéhovah seul peut sauver.", "Jonas", "Le salut appartient à Jéhovah", "Reconnaître Jéhovah comme Sauveur"),
("Zacharie 4:6", "Ce n'est ni par la force ni par la puissance, mais grâce à mon esprit, dit Jéhovah.", "L'œuvre de Jéhovah s'accomplit par son esprit.", "Jéhovah", "grâce à mon esprit", "Compter sur l'esprit de Jéhovah"),
("Matthieu 5:43", "Vous avez entendu qu'il a été dit : « Tu aimeras ton prochain et tu haïras ton ennemi. »", "Jésus corrige une interprétation erronée de la loi.", "Jésus", "haïras ton ennemi", "Rejeter la haine des ennemis"),
("Matthieu 10:22", "Vous serez haïs de tous à cause de mon nom, mais celui qui endure jusqu'à la fin sera sauvé.", "La fidélité malgré la haine mène au salut.", "Jésus", "endure jusqu'à la fin", "Endurer malgré la haine"),
("Marc 1:15", "Le temps fixé par Dieu est rempli, et le royaume de Dieu est proche. Repentez-vous.", "Jésus annonce la proximité du royaume.", "Jésus", "le royaume de Dieu est proche", "Se repentir et accueillir le royaume"),
("Luc 4:18", "L'esprit de Jéhovah est sur moi, parce qu'il m'a oint pour annoncher une bonne nouvelle aux pauvres.", "Jésus lit sa mission dans Ésaïe.", "Jésus", "annoncer une bonne nouvelle", "Participer à l'annonce"),
("Jean 5:28", "Ne vous étonnez pas de cela, car une heure vient où tous ceux qui sont dans les tombeaux entendront sa voix.", "Jésus promet la résurrection.", "Jésus", "entendront sa voix", "Croire à la résurrection"),
("Actes 2:21", "Quiconque invoque le nom de Jéhovah sera sauvé.", "L'appel au nom de Jéhovah mène au salut.", "Pierre", "invoque le nom de Jéhovah", "Invoquer le nom de Jéhovah"),
("Romains 14:19", "Poursuivons les choses qui contribuent à la paix et à l'édification.", "Rechercher la paix et édifier autrui.", "Paul", "contribuent à la paix", "Poursuivre la paix"),
("1 Corinthiens 6:19", "Ne savez-vous pas que votre corps est le temple du saint esprit en vous ?", "Notre corps doit être traité avec respect.", "Paul", "temple du saint esprit", "Respecter son corps"),
("2 Corinthiens 1:3", "Loué soit le Dieu et Père de notre Seigneur Jésus Christ, le Père des tendres compassions.", "Jéhovah est source de tendres compassions.", "Paul", "Père des tendres compassions", "Louer Jéhovah pour sa compassion"),
("Éphésiens 3:20", "À celui qui peut faire infiniment plus que tout ce que nous demandons ou concevons.", "Jéhovah dépasse nos attentes.", "Paul", "infiniment plus", "Compter sur la puissance de Jéhovah"),
("Philippiens 2:14", "Faites toutes choses sans murmures ni disputes.", "Éviter les murmures et disputes.", "Paul", "sans murmures", "Agir sans murmurer"),
("Colossiens 1:15", "Celui qui est l'image du Dieu invisible, le premier-né de toute création.", "Jésus reflète parfaitement Jéhovah.", "Paul", "image du Dieu invisible", "Reconnaître Jésus comme image de Dieu"),
("1 Thessaloniciens 3:12", "Que le Seigneur vous fasse grandir et abonder en amour les uns pour les autres.", "Paul prie pour la croissance de l'amour.", "Paul", "abonder en amour", "Grandir en amour"),
("2 Timothée 2:15", "Efforce-toi de te présenter approuvé devant Dieu, un ouvrier qui n'a pas de quoi rougir.", "Étudier la Parole avec diligence.", "Paul", "ouvrier qui n'a pas de quoi rougir", "Étudier la Parole avec soin"),
("Hébreux 13:8", "Jésus Christ est le même hier, aujourd'hui, et pour toujours.", "Jésus ne change pas.", "Paul", "le même pour toujours", "Compter sur la constance de Jésus"),
("Jacques 3:17", "La sagesse qui vient d'en haut est d'abord pure, puis pacifique.", "La vraie sagesse produit la paix.", "Jacques", "sagesse qui vient d'en haut", "Chercher la sagesse d'en haut"),
("1 Pierre 1:15", "Comme celui qui vous a appelés est saint, soyez saints dans toute votre conduite.", "Imiter la sainteté de Jéhovah.", "Pierre", "soyez saints", "Poursuivre la sainteté"),
("1 Jean 4:7", "Bien-aimés, continuons à nous aimer les uns les autres, car l'amour vient de Dieu.", "L'amour fraternel a sa source en Jéhovah.", "Jean", "l'amour vient de Dieu", "Aimer parce que Dieu aime"),
("Apocalypse 1:3", "Heureux celui qui lit à haute voix et ceux qui entendent les paroles de la prophétie.", "Lire la prophétie apporte un bonheur.", "Jean", "lit à haute voix", "Lire la prophétie"),
("Apocalypse 2:10", "Sois fidèle jusqu'à la mort, et je te donnerai la couronne de la vie.", "La fidélité jusqu'à la mort est récompensée.", "Jésus", "couronne de la vie", "Rester fidèle jusqu'à la mort"),
("Apocalypse 12:11", "Ils l'emportèrent sur lui grâce au sang de l'Agneau et grâce à la parole de leur témoignage.", "La victoire vient par Jésus et le témoignage.", "Jean", "parole de leur témoignage", "Témoigner avec courage"),
("Apocalypse 19:6", "Louez Jéhovah, car Jéhovah notre Dieu, le Tout-Puissant, a commencé à régner.", "Jéhovah commence son règne.", "Jean", "a commencé à régner", "Louer le règne de Jéhovah"),
("Apocalypse 22:17", "L'esprit et la jeune femme épousée disent : « Viens ! »", "Invitation à accepter les eaux de la vie.", "Jean", "Viens", "Accepter l'invitation de Jéhovah"),
("Néhémie 4:6", "Le peuple avait le cœur à l'ouvrage.", "L'enthousiasme du peuple pour reconstruire les murs.", "Néhémie", "cœur à l'ouvrage", "Travailler avec enthousiasme"),
("Esdras 7:10", "Car Esdras avait appliqué son cœur à étudier la loi de Jéhovah, à la pratiquer et à enseigner.", "Étudier, pratiquer et enseigner la Parole.", "Esdras", "étudier la loi de Jéhovah", "Étudier et enseigner la Parole"),
("Esther 4:14", "Et qui sait si ce n'est pas pour un moment comme celui-ci que tu es parvenue à ta position royale ?", "Esther est peut-être là pour un dessein divin.", "Mordecai", "pour un moment comme celui-ci", "Saisir les occasions de servir Jéhovah"),
("Écclésiaste 3:1", "Il y a un temps fixé pour tout, un temps pour chaque activité sous les cieux.", "Jéhovah a fixé un temps pour chaque chose.", "Salomon", "un temps fixé pour tout", "Accepter le timing de Jéhovah"),
("Écclésiaste 12:13", "La conclusion de la parole, c'est ceci : crains le vrai Dieu et observe ses commandements.", "Craindre Jéhovah et observer ses commandements résume tout.", "Salomon", "crains le vrai Dieu", "Craindre Jéhovah et obéir"),
("Cantique 8:6", "L'amour est aussi fort que la mort.", "L'amour véritable est puissant et durable.", "Salomon", "aussi fort que la mort", "Valoriser l'amour durable"),
("Matthieu 3:2", "Repentez-vous, car le royaume des cieux s'est approché.", "Jean-Baptiste appelle au repentir.", "Jean-Baptiste", "le royaume des cieux s'est approché", "Se repentir"),
("Matthieu 26:41", "Veillez et priez continuellement, afin que vous ne cédiez pas à la tentation.", "Jésus exhorte à la vigilance dans la prière.", "Jésus", "Veillez et priez", "Veiller et prier"),
("Marc 12:29", "Écoute, Israël : Jéhovah notre Dieu est un seul Jéhovah.", "Jéhovah est le seul vrai Dieu.", "Jésus", "un seul Jéhovah", "Reconnaître Jéhovah comme seul Dieu"),
("Luc 9:23", "Si quelqu'un veut venir après moi, qu'il renonce à lui-même et qu'il se charge de sa torture stake.", "Suivre Jésus demande renoncement.", "Jésus", "renonce à lui-même", "Renoncer à soi pour suivre Jésus"),
("Jean 7:17", "Si quelqu'un veut faire la volonté de Dieu, il reconnaîtra si l'enseignement vient de Dieu.", "Faire la volonté de Dieu éclaire la compréhension.", "Jésus", "faire la volonté de Dieu", "Chercher la volonté de Jéhovah"),
("Actes 16:31", "Crois au Seigneur Jésus et tu seras sauvé, toi et ta maison.", "La foi en Jésus ouvre le salut.", "Paul", "Crois au Seigneur Jésus", "Croire en Jésus"),
("Romains 5:1", "Étant donc que nous sommes déclarés justes grâce à la foi, nous avons la paix avec Dieu.", "La foi apporte la paix avec Jéhovah.", "Paul", "nous avons la paix avec Dieu", "Chercher la paix avec Jéhovah"),
("1 Corinthiens 16:14", "Que toutes vos actions se fassent avec amour.", "L'amour doit imprégner toutes nos actions.", "Paul", "se fassent avec amour", "Agir avec amour"),
("2 Corinthiens 5:20", "Nous sommes donc des ambassadeurs substituant pour Christ.", "Les chrétiens représentent Christ.", "Paul", "ambassadeurs substituant pour Christ", "Représenter Christ fidèlement"),
("Galates 5:13", "Vous avez été appelés à la liberté. Ne usez pas de votre liberté pour servir de prétexte à la chair.", "La liberté chrétienne sert à servir par amour.", "Paul", "appelés à la liberté", "Utiliser sa liberté pour servir"),
("Éphésiens 1:7", "Nous avons les libérations par le sang de celui-ci, la libération de nos péchés.", "Le sang de Jésus libère du péché.", "Paul", "libération de nos péchés", "Apprécier le sacrifice de Jésus"),
("Philippiens 3:13", "Oubliant les choses qui sont derrière, j'étends ma main vers celles qui sont devant.", "Paul avance sans regarder en arrière.", "Paul", "Oubliant les choses derrière", "Avancer sans regretter le passé"),
("Colossiens 2:6", "Par conséquent, continuez à marcher en union avec lui.", "Marcher en union avec Jésus.", "Paul", "marcher en union avec lui", "Rester unis à Jésus"),
("1 Thessaloniciens 2:12", "Pour que vous marchiez d'une manière digne de Dieu.", "Vivre d'une manière digne de Jéhovah.", "Paul", "digne de Dieu", "Vivre dignement"),
("2 Timothée 4:7", "J'ai combattu le bon combat, j'ai achevé la course, j'ai gardé la foi.", "Paul achève sa vie avec fidélité.", "Paul", "j'ai gardé la foi", "Combattre et garder la foi"),
("Hébreux 3:13", "Exhortons-nous les uns les autres chaque jour.", "S'encourager mutuellement chaque jour.", "Paul", "Exhortons-nous chaque jour", "Encourager ses frères quotidiennement"),
("Jacques 4:10", "Humiliez-vous devant Jéhovah, et il vous élèvera.", "L'humilité mène à l'exaltation par Jéhovah.", "Jacques", "il vous élèvera", "S'humilier devant Jéhovah"),
("1 Pierre 1:7", "Afin que votre foi, qui a beaucoup plus de valeur que l'or qui périt, soit trouvée digne de louange.", "La foi est plus précieuse que l'or.", "Pierre", "foi plus précieuse que l'or", "Valoriser sa foi"),
("1 Jean 5:14", "Voici la confiance que nous avons en lui : si nous demandons quoi que ce soit selon sa volonté, il nous écoute.", "Jéhovah écoute les prières conformes à sa volonté.", "Jean", "selon sa volonté", "Prier selon la volonté de Jéhovah"),
("Apocalypse 5:12", "L'Agneau qui a été immolé est digne de recevoir la puissance, la richesse, la sagesse, la force, l'honneur, la gloire et la louange.", "Jésus l'Agneau mérite toute louange.", "Jean", "digne de recevoir la louange", "Louer l'Agneau Jésus"),
("Apocalypse 15:3", "Grande et merveilleuses sont tes œuvres, Jéhovah Dieu, le Tout-Puissant.", "Les œuvres de Jéhovah sont merveilleuses.", "Jean", "merveilleuses sont tes œuvres", "Admirer les œuvres de Jéhovah"),
("Matthieu 2:11", "Ils ouvrirent leurs trésors et lui offrirent des cadeaux : de l'or, de l'encens et du myrrhe.", "Les mages offrent des cadeaux au jeune Jésus.", "Matthieu", "lui offrirent des cadeaux", "Offrir le meilleur à Jésus"),
("Matthieu 8:26", "Pourquoi avez-vous peur, hommes de peu de foi ?", "Jésus calme la tempête et questionne la foi des disciples.", "Jésus", "hommes de peu de foi", "Renforcer sa foi face à la peur"),
("Luc 15:10", "De même, je vous dis, il y a de la joie devant les anges de Dieu pour un seul pécheur qui se repent.", "Les anges se réjouissent du repentir d'un pécheur.", "Jésus", "joie devant les anges de Dieu", "Se réjouir du repentir"),
("Jean 14:27", "Je vous laisse la paix, je vous donne ma paix.", "Jésus offre une paix unique.", "Jésus", "je vous donne ma paix", "Accepter la paix de Jésus"),
("Actes 1:11", "Ce Jésus qui a été enlevé au ciel reviendra de la même manière.", "Jésus reviendra visiblement.", "Les anges", "reviendra de la même manière", "Attendre le retour de Jésus"),
("Romains 8:16", "L'esprit lui-même rend témoignage avec notre esprit que nous sommes enfants de Dieu.", "L'esprit confirme notre filiation.", "Paul", "enfants de Dieu", "Reconnaître sa filiation"),
("1 Corinthiens 15:33", "Ne vous y trompez pas : les mauvaises compagnies corrompent les bonnes mœurs.", "Les fréquentations influencent notre conduite.", "Paul", "mauvaises compagnies", "Choisir de bonnes fréquentations"),
("2 Corinthiens 12:9", "Ma puissance s'achève dans ta faiblesse.", "La force de Jéhovah se manifeste dans notre faiblesse.", "Jésus", "Ma puissance s'achève dans ta faiblesse", "Compter sur la force de Jéhovah"),
("Éphésiens 6:11", "Revêtez-vous de l'armure complète de Dieu.", "Se préparer spirituellement pour les épreuves.", "Paul", "armure complète de Dieu", "Se revêtir de l'armure spirituelle"),
("Philippiens 1:10", "Afin que vous puissiez approuver les choses qui sont excellentes.", "Discerner ce qui est excellent.", "Paul", "choses qui sont excellentes", "Discerner le bien"),
("Colossiens 3:2", "Continuez à penser aux choses d'en haut, pas à celles sur la terre.", "Fixer son mental sur les choses spirituelles.", "Paul", "choses d'en haut", "Penser aux choses spirituelles"),
("1 Timothée 6:6", "La piété, accompagnée du contentement, est un grand moyen de gain.", "La piété avec contentement est une vraie richesse.", "Paul", "piété, accompagnée du contentement", "Cultiver piété et contentement"),
("Hébreux 12:2", "Gardez les yeux fixés sur Jésus, le chef et le précurseur de la foi.", "Fixer les yeux sur Jésus pour tenir bon.", "Paul", "fixés sur Jésus", "Fixer les yeux sur Jésus"),
("Jacques 3:1", "Mes frères, que peu d'entre vous deviennent des enseignants.", "Enseigner est une lourde responsabilité.", "Jacques", "deviennent des enseignants", "Prendre au sérieux l'enseignement"),
("1 Pierre 2:21", "Christ a souffert pour vous, vous laissant un modèle.", "Jésus est modèle dans la souffrance.", "Pierre", "vous laissant un modèle", "Imiter Jésus dans la souffrance"),
("1 Jean 2:6", "Celui qui dit qu'il reste en union avec lui, doit marcher comme il a marché.", "Rester en union avec Jésus implique imiter sa conduite.", "Jean", "marcher comme il a marché", "Marcher comme Jésus"),
("Apocalypse 3:15", "Je connais tes œuvres, que tu n'es ni froid ni chaud.", "Jésus exhorte à la ferveur, pas à l'indifférence.", "Jésus", "ni froid ni chaud", "Être fervent dans sa foi"),
("Apocalypse 21:5", "Voici, je fais toutes choses nouvelles.", "Jéhovah promet un renouvellement complet.", "Jéhovah", "toutes choses nouvelles", "Attendre le renouvellement promis"),
("Deutéronome 6:5", "Tu aimeras Jéhovah ton Dieu de tout ton cœur, de toute ton âme et de toute ta force.", "Le Shema commande l'amour total pour Jéhovah.", "Moïse", "de toute ta force", "Aimer Jéhovah de tout son être"),
("Deutéronome 31:6", "Soyez forts et courageux. Ne craignez pas et ne soyez pas terrifiés, car Jéhovah votre Dieu marche avec vous.", "Jéhovah marche avec son peuple.", "Moïse", "marche avec vous", "Avoir courage avec Jéhovah"),
("Josué 24:15", "Quant à moi et ma maison, nous servirons Jéhovah.", "Josué choisit explicitement de servir Jéhovah.", "Josué", "nous servirons Jéhovah", "Choisir de servir Jéhovah"),
("Psaume 18:2", "Jéhovah est mon rocher, ma forteresse et mon libérateur.", "David proclame Jéhovah comme protecteur.", "David", "mon rocher, ma forteresse", "Voir Jéhovah comme protecteur"),
("Psaume 32:8", "Je t'instruirai et te montrerai la voie à suivre ; je te conseillerai, mon œil sera sur toi.", "Jéhovah guide et conseille.", "David", "Je t'instruirai", "Accepter la guidance de Jéhovah"),
("Psaume 86:11", "Instruis-moi, ô Jéhovah, dans ta voie. Je marcherai dans ta vérité.", "David demande à marcher dans la vérité de Jéhovah.", "David", "marcherai dans ta vérité", "Marcher dans la vérité de Jéhovah"),
("Psaume 103:12", "Dans la mesure où le levant est éloigné du couchant, il a éloigné nos transgressions de nous.", "Jéhovah éloigne nos péchés quand il pardonne.", "David", "éloigné nos transgressions", "Apprécier le pardon de Jéhovah"),
("Psaume 118:6", "Jéhovah est de mon côté ; je ne craindrai pas.", "Avec Jéhovah, pas de crainte.", "Anonyme", "Je ne craindrai pas", "Ne pas craindre avec Jéhovah"),
("Psaume 130:5", "J'attends Jéhovah, mon âme l'attend, et je place ma confiance en sa parole.", "Attendre Jéhovah avec confiance.", "Anonyme", "je place ma confiance en sa parole", "Attendre Jéhovah patiemment"),
("Proverbes 2:6", "Car c'est Jéhovah qui donne la sagesse ; de sa bouche viennent la connaissance et la réflexion.", "La sagesse vient de Jéhovah.", "Salomon", "Jéhovah qui donne la sagesse", "Demander la sagesse à Jéhovah"),
("Proverbes 14:12", "Il existe une voie qui paraît droite à l'homme, mais au bout de cette voie, c'est la mort.", "Nos jugements peuvent nous tromper.", "Salomon", "paraît droite à l'homme", "Ne pas se fier à son propre jugement"),
("Proverbes 19:21", "Il existe beaucoup de projets dans le cœur de l'homme, mais c'est le dessein de Jéhovah qui s'accomplit.", "Le dessein de Jéhovah prévaut.", "Salomon", "dessein de Jéhovah", "Accepter le dessein de Jéhovah"),
("Ésaïe 43:2", "Si tu traverses des eaux, je serai avec toi.", "Jéhovah promet sa présence dans l'épreuve.", "Jéhovah", "je serai avec toi", "Compter sur Jéhovah dans l'épreuve"),
("Jérémie 33:3", "Invoque-moi, et je te répondrai ; je te révélerai de grandes choses.", "Jéhovah répond à l'invocation.", "Jéhovah", "je te répondrai", "Invoquer Jéhovah"),
("Matthieu 5:48", "Vous devez donc être parfaits, comme votre Père céleste est parfait.", "Imiter la perfection du Père céleste.", "Jésus", "comme votre Père céleste est parfait", "Poursuivre la perfection morale"),
("Jean 15:16", "Ce n'est pas vous qui m'avez choisi, mais c'est moi qui vous ai choisis.", "Jésus a choisi ses disciples.", "Jésus", "moi qui vous ai choisis", "Répondre à l'appel de Jésus"),
("Romains 12:18", "Si possible, autant que cela dépend de vous, soyez en paix avec tous les hommes.", "Rechercher la paix avec tous.", "Paul", "soyez en paix avec tous", "Rechercher la paix"),
("1 Corinthiens 10:31", "Que toutes vos actions se fassent pour la gloire de Dieu.", "Glorifier Jéhovah en tout.", "Paul", "pour la gloire de Dieu", "Agir pour la gloire de Jéhovah"),
("Galates 6:2", "Portez les fardeaux les uns des autres, et vous remplirez ainsi la loi du Christ.", "Supporter les fardeaux mutuellement.", "Paul", "Portez les fardeaux", "Aider ses frères dans leurs fardeaux"),
("Éphésiens 5:19", "Parlez-vous les uns aux autres avec des psaumes, des louanges.", "Encourager par des chants et louanges.", "Paul", "psaumes, des louanges", "Encourager par la louange"),
("Philippiens 4:19", "Mon Dieu pourvoira à tout ce dont vous avez besoin.", "Jéhovah pourvoit à nos besoins.", "Paul", "pourvoira à tout ce dont vous avez besoin", "Confier ses besoins à Jéhovah"),
("1 Timothée 4:8", "La piété est profitable à tout.", "La piété apporte des bénéfices durables.", "Paul", "La piété est profitable", "Cultiver la piété"),
("Hébreux 6:10", "Dieu n'est pas injuste pour oublier votre travail et l'amour que vous avez montré pour son nom.", "Jéhovah n'oublie pas notre service.", "Paul", "n'oublie pas votre travail", "Servir Jéhovah avec constance"),
("Jacques 5:8", "Soyez aussi patients ; faites bonne contenance jusqu'à la venue du Seigneur.", "Patience en attendant le retour de Jésus.", "Jacques", "jusqu'à la venue du Seigneur", "Patienter jusqu'au retour de Jésus"),
("1 Pierre 4:10", "Servez-vous les uns les autres, chacun selon le don qu'il a reçu, comme de bons gérants.", "Utiliser nos dons pour servir les frères.", "Pierre", "Servez-vous les uns les autres", "Servir avec les dons reçus"),
("1 Jean 3:1", "Voyez quel amour le Père nous a manifesté, pour que nous soyons appelés enfants de Dieu !", "Jéhovah nous appelle ses enfants par amour.", "Jean", "enfants de Dieu", "Apprécier notre relation avec Jéhovah"),
("Apocalypse 4:8", "Saint, saint, saint est Jéhovah Dieu, le Tout-Puissant.", "Les créatures célestes proclament la sainteté de Jéhovah.", "Les vivants", "Saint, saint, saint", "Proclamer la sainteté de Jéhovah"),
("Josué 1:9", "Ne t'ai-je pas ordonné : sois ferme et courageux ? Ne t'effraie pas, car Jéhovah ton Dieu est avec toi.", "Jéhovah exhorte Josué à la fermeté. Sa présence est la source du courage.", "Jéhovah", "ferme et courageux", "Faire preuve de courage avec Jéhovah"),
("Juges 6:12", "Jéhovah est avec toi, vaillant guerrier.", "L'ange s'adresse à Gédéon alors qu'il se sent faible.", "L'ange de Jéhovah", "Jéhovah est avec toi", "Accepter que Jéhovah voit notre valeur"),
("Ruth 1:16", "Là où tu iras j'irai… Ton peuple sera mon peuple et ton Dieu mon Dieu.", "Ruth manifeste une loyauté remarquable envers Naomi et Jéhovah.", "Ruth", "Ton peuple sera mon peuple", "Faire preuve de loyauté"),
("1 Samuel 16:7", "L'homme voit ce qui paraît aux yeux, mais Jéhovah voit le cœur.", "Jéhovah choisit David pour son cœur, non pour son apparence.", "Jéhovah via Samuel", "Jéhovah voit le cœur", "Cultiver un cœur agréable à Jéhovah"),
("2 Samuel 22:31", "Le chemin de Dieu est parfait ; la parole de Jéhovah est affinée.", "David loue la perfection des voies de Jéhovah.", "David", "Le chemin de Dieu est parfait", "Faire confiance aux voies de Jéhovah"),
("1 Rois 3:9", "Accorde à ton serviteur un cœur obéissant pour juger ton peuple.", "Salomon demande la sagesse plutôt que la richesse.", "Salomon", "un cœur obéissant", "Demander la sagesse à Jéhovah"),
("2 Rois 6:16", "Ne crains pas, car ceux qui sont avec nous sont plus nombreux.", "Élisée rassure son serviteur face à l'armée ennemie.", "Élisée", "plus nombreux que ceux qui sont avec eux", "Ne pas craindre avec Jéhovah"),
("Néhémie 8:10", "La joie de Jéhovah est votre force.", "Néhémie encourage le peuple à trouver sa force en Jéhovah.", "Néhémie", "La joie de Jéhovah", "Trouver sa force en Jéhovah"),
("Job 1:21", "Jéhovah a donné, et Jéhovah a pris. Que le nom de Jéhovah soit béni.", "Job bénit Jéhovah même dans l'adversité.", "Job", "Que le nom de Jéhovah soit béni", "Bénir Jéhovah dans l'épreuve"),
("Job 42:5", "Mes oreilles avaient entendu parler de toi, mais maintenant mon œil t'a vu.", "Après l'épreuve, Job comprend mieux Jéhovah.", "Job", "mon œil t'a vu", "Approfondir sa connaissance de Jéhovah"),
("Psaume 1:1", "Heureux l'homme qui ne marche pas selon le conseil des méchants.", "Le bonheur de celui qui évite les mauvaises influences.", "David", "ne marche pas selon le conseil des méchants", "Éviter les mauvaises influences"),
("Psaume 19:14", "Que les paroles de ma bouche et les pensées de mon cœur te soient agréables, ô Jéhovah.", "David prie pour que ses paroles plaisent à Jéhovah.", "David", "paroles de ma bouche", "Surveiller nos paroles et pensées"),
("Psaume 37:4", "Fais plaisir à Jéhovah, et il te donnera les demandes de ton cœur.", "Quand nos désirs s'alignent avec Jéhovah, il comble nos aspirations.", "David", "Fais plaisir à Jéhovah", "Aligner nos désirs avec Jéhovah"),
("Psaume 91:1", "Celui qui habite sous le secret du Très-Haut passera la nuit à l'ombre du Tout-Puissant.", "Jéhovah protège ceux qui demeurent près de lui.", "Moïse", "l'ombre du Tout-Puissant", "Demeurer près de Jéhovah"),
("Psaume 119:105", "Ta parole est une lampe à mes pieds et une lumière sur mon sentier.", "La Parole de Jéhovah éclaire notre chemin.", "Anonyme", "lampe à mes pieds", "Laisser la Bible guider nos pas"),
]

lines = ["# Part 3", "def add(s, r, t, sp, k, a):", "    DATA.append((s, r, t, sp, k, a))", ""]
for r, s, t, sp, k, a in POOL:
    lines.append(f"add({s!r}, {r!r}, {t!r}, {sp!r}, {k!r}, {a!r})")
with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print(f"Wrote {len(POOL)} to part3")
